# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('fbpagelink', models.URLField()),
                ('address', models.TextField()),
                ('meetuplink', models.URLField()),
                ('polynteer', models.BooleanField()),
                ('eventshosted', models.SmallIntegerField()),
                ('eventshostedname', models.CharField(max_length=200)),
                ('ohb', models.BooleanField()),
                ('ohbcontributions', models.SmallIntegerField()),
                ('launchteam', models.BooleanField()),
                ('launchteamcontributions', models.SmallIntegerField()),
                ('fbgroupmember', models.BooleanField()),
                ('donationtotalammount', models.SmallIntegerField()),
            ],
        ),
    ]
