# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitycrmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='eventshosted',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='meetuplink',
        ),
        migrations.RemoveField(
            model_name='member',
            name='polynteer',
        ),
        migrations.AddField(
            model_name='member',
            name='meetupid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='volunteer',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='fbgroupmember',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='launchteam',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='ohb',
            field=models.NullBooleanField(),
        ),
    ]
